openapi: 3.0.0
info:
  title: Kubernetes Demo Rest API
  description: File Upload and User CRUD operations API description
  version: 1.0.0
  termsOfService: http://localhost:8080/terms-of-use
  contact:
    email: pratap.ak@nsc.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Reflectoring
  url: https://reflectoring.io/about/
servers:
  - url: http://localhost:8080/api/v1
  - url: http://localhost:8080/api/v2
paths:
  /movie/{movieId}:
    get:
      summary: get movie by movieId
      operationId: getMovieById
      parameters:
        - name: movieId
          in: path
          description: movieId from which movie should be fetched
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
              example:
                movieId: apth123
                movieName: Apthamitra
        404:
          description: Not found
          content: {}
      security: # security for specific API
        - api_key: []
components:
  schemas:
    Movie:
      type: object
      properties:
        movieId:
          type: string
        movieName:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

