apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pratap-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pratap-persistent-volume
  volumeMode: Filesystem
  storageClassName: pratap-storage-class
