apiVersion: v1
kind: Secret
metadata:
  name: pratap-demo-secret
type: Opaque
data:
  username: ZGJfdXNlcg==
  password: ZGJfdXNlcl9wYXNz
stringData: # for non-base64 encoded data
  apiUrl: "https://my.api.com/api/v1" # non-base64 encoded
# secrets should not be created using yaml files since data is only base 64 encoded. If this file exist in source control
# anyone can decode the secret
# get password as env variables
